name: RABI_TRACK
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.0.0 # Check for the latest version
  http: ^1.2.2  # Update to the latest version
  shared_preferences: ^2.0.15
  jwt_decode: ^0.3.1

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Rabitrackrivertr-modified.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/River_Logo.png
    - assets/aic_logo.png
    - assets/logo.png
    - assets/ptu-logo.png
    - assets/google_map.png
    - assets/rabitrack.jpeg
    - assets/doodle.png
    - assets/doctor.jpg
    - assets/doctorbg.png
    - assets/Rabitrackrivertr.png
    - assets/Rabitrackrivertr-modified.png

    - assets/background.png
    - assets/bg.avif
    - assets/bg1.avif
    - assets/crop.png
  # You can add custom fonts to your application here
  fonts:
    - family: Averia Gruesa Libre
      fonts:
        - asset: fonts/AveriaGruesaLibre-Regular.ttf
